Section "Device"
    Identifier "SLOT-GUARD Waveshare LCD"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "InputClass"
    Identifier "SLOT-GUARD touch calibration"
    MatchProduct "ADS7846 Touchscreen"
    Driver "evdev"
    Option "Calibration" "3950 172 3871 194"
    Option "SwapAxes" "1"
EndSection
