#!/bin/sh
set -eu

xset s off
xset -dpms
xset s noblank

/usr/bin/openbox --config-file /etc/xdg/openbox/rc.xml &

until /usr/bin/curl --silent --fail --max-time 2 \
    http://127.0.0.1:5000/api/display-status >/dev/null; do
    sleep 1
done

exec /usr/bin/chromium \
    --kiosk \
    --app=http://127.0.0.1:5000/display \
    --user-data-dir="$HOME/.config/slotguard-chromium" \
    --lang=ko-KR \
    --password-store=basic \
    --disable-sync \
    --disable-extensions \
    --disable-component-update \
    --disable-translate \
    --no-first-run \
    --disable-pinch \
    --disable-features=Translate,TranslateUI \
    --disable-session-crashed-bubble \
    --noerrdialogs \
    --overscroll-history-navigation=0
