#!/usr/bin/python3
import sys
import time
from datetime import datetime, timezone


MIN_TIMESTAMP_SECONDS = int(
    datetime(2024, 1, 1, tzinfo=timezone.utc).timestamp()
)
MAX_TIMESTAMP_SECONDS = int(
    datetime(2100, 1, 1, tzinfo=timezone.utc).timestamp()
)


def main():
    if len(sys.argv) != 2 or not sys.argv[1].isdigit():
        print(
            "usage: slotguard-set-time <unix-timestamp-seconds>",
            file=sys.stderr,
        )
        return 2

    timestamp_seconds = int(sys.argv[1])

    if not (
        MIN_TIMESTAMP_SECONDS
        <= timestamp_seconds
        < MAX_TIMESTAMP_SECONDS
    ):
        print(
            "timestamp must be between 2024-01-01 and 2099-12-31",
            file=sys.stderr,
        )
        return 2

    try:
        time.clock_settime(
            time.CLOCK_REALTIME,
            float(timestamp_seconds),
        )
    except (OSError, PermissionError) as error:
        print(f"failed to set system time: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())

